% Compare Pure Pursuit, PINN Drive, and NN AI step responses on one graph.
% The script expects CSV logs generated by the ROS controllers.

clear; clc; close all;

% Use the script folder as default data directory.
scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end

files = {
    'Pure Pursuit', 'pure_pursuit_step_response.csv';
    'PINN Drive',   'pinn_drive_step_response.csv';
    'NN AI',        'nn_ai_step_response.csv';
};

figure('Color', 'w', 'Name', 'Three-Controller Lateral and Heading Step Response');

ax1 = subplot(2,1,1);
hold(ax1, 'on');
grid(ax1, 'on');

ax2 = subplot(2,1,2);
hold(ax2, 'on');
grid(ax2, 'on');

plottedCount = 0;
yawPlottedCount = 0;

for k = 1:size(files, 1)
    controllerName = files{k, 1};
    csvName = files{k, 2};
    csvPath = fullfile(scriptDir, csvName);

    if ~isfile(csvPath)
        warning('%s missing: %s', controllerName, csvPath);
        continue;
    end

    T = readtable(csvPath);

    % Require time axis.
    if ~ismember('time_s', T.Properties.VariableNames)
        warning('%s skipped: time_s column not found.', controllerName);
        continue;
    end

    t = T.time_s;

    % Extract y-axis data for step response
    requiredCols = {'desired_y','actual_y'};
    if ~all(ismember(requiredCols, T.Properties.VariableNames))
        warning('%s skipped: desired_y and actual_y columns required.', controllerName);
        continue;
    end

    desiredY = T.desired_y;
    actualY = T.actual_y;
    yError = desiredY - actualY;

    valid = isfinite(t) & isfinite(yError) & isfinite(actualY) & isfinite(desiredY);

    t = t(valid);
    yError = yError(valid);
    actualY = actualY(valid);
    desiredY = desiredY(valid);

    if numel(t) < 2
        warning('%s skipped: not enough valid samples.', controllerName);
        continue;
    end

    % Keep a common time origin while preserving raw response magnitude.
    t = t - t(1);

    plot(ax1, t, yError, 'LineWidth', 2, 'DisplayName', controllerName);
    plottedCount = plottedCount + 1;

    % Plot heading error response from the same CSV when available.
    if ismember('yaw_error', T.Properties.VariableNames)
        yawErr = T.yaw_error;
        yawValid = valid & isfinite(yawErr);
        if nnz(yawValid) >= 2
            tYawRaw = T.time_s(yawValid);
            tYaw = tYawRaw - tYawRaw(1);
            yawErr = yawErr(yawValid);
            plot(ax2, tYaw, yawErr, 'LineWidth', 2, 'DisplayName', controllerName);
            yawPlottedCount = yawPlottedCount + 1;
        end
    end
end

yline(ax1, 0.0, '--k', 'Target (zero y-error)', 'LineWidth', 1.2, 'DisplayName', 'Target');
yline(ax2, 0.0, '--k', 'Target (zero yaw-error)', 'LineWidth', 1.2, 'DisplayName', 'Target');

xlabel(ax1, 'Time [s]');
ylabel(ax1, 'Y-Axis Error [m]');
title(ax1, 'Y-Axis Step Response Comparison (desired_y - actual_y)');
legend(ax1, 'Location', 'best');

xlabel(ax2, 'Time [s]');
ylabel(ax2, 'Yaw Error [rad]');
title(ax2, 'Heading Step Response Comparison (desired_yaw - actual_yaw)');
if yawPlottedCount > 0
    legend(ax2, 'Location', 'best');
end

if plottedCount == 0
    error('No valid controller datasets were plotted. Check CSV files and columns.');
end

if yawPlottedCount == 0
    warning('No yaw_error column data found to plot heading response.');
end
